import { Product, CurrencyConfig } from './types';

export const CURRENCIES: Record<string, CurrencyConfig> = {
  PKR: { code: 'PKR', symbol: 'Rs.', rate: 1 },
  USD: { code: 'USD', symbol: '$', rate: 0.0036 },
  AED: { code: 'AED', symbol: 'AED', rate: 0.013 },
  GBP: { code: 'GBP', symbol: '£', rate: 0.0028 },
  SAR: { code: 'SAR', symbol: 'SAR', rate: 0.0135 },
};

export const PRODUCTS: Product[] = [
  {
    id: 'noor-festive-3pc',
    title: 'Noor-e-Khaas Embroidered Festive Lawn',
    collection: 'Festive Luxury 2026',
    category: 'unstitched',
    categoryLabel: 'Unstitched Luxury',
    pricePKR: 9850,
    originalPricePKR: 11500,
    image: '/images/hero_campaign.jpg',
    gallery: [
      '/images/hero_campaign.jpg',
      '/images/women_pret.jpg',
      '/images/shawl_craft.jpg',
    ],
    fabric: 'Swiss Voile Lawn & Zari Organza',
    pieces: '3-Piece Unstitched',
    description: 'An ode to Mughal grandeur and timeless Eastern craftsmanship. Featuring an intricately embroidered front with delicate sequin and zari flourishes, paired with a dyed cambric trouser and an opulent digital printed jacquard organza dupatta.',
    details: [
      'Embroidered Swiss Lawn Front with Zari & Hand-finished Tilla (1.25m)',
      'Digital Printed Lawn Back & Sleeves (1.75m)',
      'Embroidered Organza Front & Hem Cutwork Border (1m)',
      'Dyed Fine Cambric Cotton Trouser (2.5m)',
      'Luxury Zari Woven Jacquard Dupatta with Embroidered Pallu (2.5m)',
    ],
    sizes: ['Unstitched', 'Custom Stitching'],
    colors: [
      { colorName: 'Pistachio Mint', colorHex: '#9fb39c', image: '/images/hero_campaign.jpg' },
      { colorName: 'Blush Ivory', colorHex: '#e8ded4', image: '/images/women_pret.jpg' },
    ],
    isNewArrival: true,
    isBestseller: true,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 38,
    reviews: [
      {
        id: 'r1',
        author: 'Ayesha Farooq',
        city: 'Lahore (Defence)',
        rating: 5,
        date: '3 days ago',
        comment: 'The fabric quality is extraordinary! Even richer in person than photos. The zari border work gives a regal look for family weddings.',
        verified: true,
      },
      {
        id: 'r2',
        author: 'Dr. Maria Siddiqui',
        city: 'Karachi (Clifton)',
        rating: 5,
        date: '1 week ago',
        comment: 'Reminds me of the best Khaadi Khas collections. Soft breathable lawn and very neat embroidery threadwork.',
        verified: true,
      },
    ],
    careInstructions: [
      'Dry clean recommended for first wash',
      'Do not bleach or tumble dry',
      'Iron at moderate temperature inside out',
    ],
  },
  {
    id: 'gul-e-rana-pret',
    title: 'Gul-e-Rana Embroidered Pret Kurta',
    collection: 'Summer Pret 2026',
    category: 'women-pret',
    categoryLabel: 'Ready-to-Wear Pret',
    pricePKR: 5450,
    originalPricePKR: 6200,
    image: '/images/women_pret.jpg',
    gallery: [
      '/images/women_pret.jpg',
      '/images/hero_campaign.jpg',
    ],
    fabric: 'Pure Cotton Jacquard',
    pieces: 'Ready to Wear 2-Piece',
    description: 'Elevate your daytime gatherings with this meticulously tailored blush pink silhouette. Styled with artisanal resham threadwork along the neckline, loop button placket, and breezy flared bell sleeves.',
    details: [
      'Subtle self-textured pure cotton jacquard fabric',
      'Resham and pearl hand-embellished round band collar',
      'Flared silhouette with scalloped organza lace detailing',
      'Matched straight-cut cigarette pants with pintuck accents',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { colorName: 'Blush Pink', colorHex: '#e3b5b5', image: '/images/women_pret.jpg' },
      { colorName: 'Sage Mint', colorHex: '#a7b8a2', image: '/images/hero_campaign.jpg' },
    ],
    isNewArrival: true,
    isBestseller: true,
    isOnSale: false,
    rating: 4.8,
    reviewsCount: 52,
    reviews: [
      {
        id: 'r3',
        author: 'Sana Tariq',
        city: 'Islamabad (F-8)',
        rating: 5,
        date: '2 days ago',
        comment: 'Perfect fitting in Small! The cotton jacquard is so light and perfect for summer weather. Received so many compliments.',
        verified: true,
      },
    ],
    careInstructions: [
      'Gentle machine wash or hand wash in cold water',
      'Wash dark colors separately',
      'Steam iron for best finish',
    ],
  },
  {
    id: 'sultan-royal-latha-men',
    title: 'Sultan Royal Egyptian Latha Kurta Shalwar',
    collection: 'Heritage Men 2026',
    category: 'men',
    categoryLabel: "Men's Traditional",
    pricePKR: 6850,
    originalPricePKR: 7500,
    image: '/images/men_kurta.jpg',
    gallery: [
      '/images/men_kurta.jpg',
    ],
    fabric: '100% Giza Egyptian Long-Staple Cotton',
    pieces: '2-Piece Kurta Shalwar',
    description: 'A classic staple of Eastern heritage favored by gentlemen. Woven from 100% genuine Egyptian Giza cotton with a crisp, lustrous latha fall. Features a classic band collar, tailored cuffs, and genuine mother-of-pearl buttons.',
    details: [
      'Traditional stiff-finish Royal Latha weave with natural luster',
      'Mandarin ban collar with subtle tonal thread embroidery',
      'Dual side pockets and front chest pocket',
      'Full volume traditional shalwar with neat pleats',
      'Signature engraved horn buttons',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { colorName: 'Crisp White', colorHex: '#fcfcfc', image: '/images/men_kurta.jpg' },
      { colorName: 'Off-White Ivory', colorHex: '#f2eee9', image: '/images/men_kurta.jpg' },
    ],
    isNewArrival: false,
    isBestseller: true,
    isOnSale: false,
    rating: 5.0,
    reviewsCount: 94,
    reviews: [
      {
        id: 'r4',
        author: 'Hamza Malik',
        city: 'Rawalpindi',
        rating: 5,
        date: '5 days ago',
        comment: 'Equal to or even better than J. Latha! The fall of the fabric and the crisp collar are top tier. Delivery within 2 days via TCS.',
        verified: true,
      },
      {
        id: 'r5',
        author: 'Usman Sheikh',
        city: 'Faisalabad',
        rating: 5,
        date: '2 weeks ago',
        comment: 'Authentic 100% Egyptian cotton. Will definitely order the Off-White variant as well for Jummah.',
        verified: true,
      },
    ],
    careInstructions: [
      'Gentle hand wash with mild detergent',
      'Starch lightly if crisp traditional fall is desired',
      'Dry in shade to preserve crisp brilliance',
    ],
  },
  {
    id: 'virasat-raw-silk-waistcoat',
    title: 'Virasat Embroidered Raw Silk Waistcoat',
    collection: 'Heritage Men 2026',
    category: 'men',
    categoryLabel: "Men's Formal",
    pricePKR: 7490,
    originalPricePKR: 8500,
    image: '/images/men_kurta.jpg',
    gallery: [
      '/images/men_kurta.jpg',
    ],
    fabric: 'Pure Raw Silk with Tonal Zari Work',
    pieces: 'Waistcoat',
    description: 'Distinguished formal layering designed for festive and celebratory events. Expertly crafted in textured charcoal raw silk with delicate antique tonal threadwork along the band and pockets.',
    details: [
      'Tailored structured fit with premium canvas inner interlining',
      'Band collar with antique brass metallic buttons',
      'Chest welt pocket with attached silk pocket square accent',
      'Satin inner lining with two internal security pockets',
    ],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)'],
    colors: [
      { colorName: 'Charcoal Black', colorHex: '#262626', image: '/images/men_kurta.jpg' },
      { colorName: 'Midnight Navy', colorHex: '#1e293b', image: '/images/men_kurta.jpg' },
    ],
    isNewArrival: true,
    isBestseller: true,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 41,
    reviews: [
      {
        id: 'r6',
        author: 'Bilal Khan',
        city: 'Karachi (PECHS)',
        rating: 5,
        date: '4 days ago',
        comment: 'Paired it with a white Kurta Shalwar for my brother’s Nikah ceremony. Everyone asked where I bought it!',
        verified: true,
      },
    ],
    careInstructions: [
      'Strictly dry clean only',
      'Store in a breathable garment bag with cedar blocks',
    ],
  },
  {
    id: 'oud-al-malik-fragrance',
    title: 'Oud Al-Malik Eau De Parfum (100ml)',
    collection: 'Signature Fragrances',
    category: 'fragrances',
    categoryLabel: 'Artisanal Perfumes',
    pricePKR: 6250,
    originalPricePKR: 7500,
    image: '/images/luxury_oud.jpg',
    gallery: [
      '/images/luxury_oud.jpg',
    ],
    fabric: '100ml Heavy Crystal Flacon & Pure Perfume Oils',
    pieces: '100ml EDP Flacon',
    description: 'Inspired by the imperial perfumery of Eastern royalty. Opening with a magnificent blend of rare Cambodian Dehn Al-Oud and spiced saffron, melting into a heart of Taif damask rose and settling on velvety amber, smoky birch, and royal Mysore sandalwood.',
    details: [
      'Top Notes: Cambodian Oud, Saffron, Bergamot',
      'Heart Notes: Bulgarian Rose, Patchouli, Cashmere Wood',
      'Base Notes: Mysore Sandalwood, Golden Amber, Smoked Cedar',
      'Concentration: Eau De Parfum (25% Oil Concentration)',
      'Projection & Longevity: 12+ Hours lasting on skin and fabric',
    ],
    sizes: ['100ml EDP', '50ml Travel', '12ml Pure Attar'],
    colors: [
      { colorName: 'Royal Obsidian & Gold', colorHex: '#1a1a1a', image: '/images/luxury_oud.jpg' },
    ],
    isNewArrival: false,
    isBestseller: true,
    isOnSale: true,
    rating: 4.95,
    reviewsCount: 118,
    reviews: [
      {
        id: 'r7',
        author: 'Zain Ul Abideen',
        city: 'Lahore (Gulberg)',
        rating: 5,
        date: '1 day ago',
        comment: 'Hands down the best Eastern oud on the market. Better lasting than J. Janan and much smoother than commercial synthetic perfumes.',
        verified: true,
      },
      {
        id: 'r8',
        author: 'Farhan Qureshi',
        city: 'Dubai (Downtown)',
        rating: 5,
        date: '3 weeks ago',
        comment: 'Rich, oriental, and majestic. Sillage fills the room without being overpowering. 10/10 presentation box as well.',
        verified: true,
      },
    ],
    careInstructions: [
      'Keep away from direct sunlight and heat',
      'Apply to pulse points and fabric for maximum projection',
    ],
  },
  {
    id: 'kashmiri-tilla-shawl',
    title: 'Kashmiri Handwoven Zari Pashmina Shawl',
    collection: 'Artisanal Weaves',
    category: 'shawls',
    categoryLabel: 'Luxury Wool Shawls',
    pricePKR: 11500,
    originalPricePKR: 13900,
    image: '/images/shawl_craft.jpg',
    gallery: [
      '/images/shawl_craft.jpg',
      '/images/hero_campaign.jpg',
    ],
    fabric: '100% Pure Fine Cashmere & Pashmina Wool',
    pieces: 'Single Artisan Shawl (2.5 x 1.25m)',
    description: 'Handcrafted on traditional wooden looms in the valleys of Kashmir. Woven from ultra-fine pashmina wool and accented with intricate antique gold tilla needlework along all four borders. A heirloom treasure passed down generations.',
    details: [
      '100% Grade-A Pure Himalayan Cashmere Wool',
      'Authentic hand-embroidered antique tilla thread border',
      'Featherlight warmth suitable for winter evenings and formal galas',
      'Hand-twisted fringed edges',
    ],
    sizes: ['Standard Heirloom (2.5m x 1.25m)'],
    colors: [
      { colorName: 'Antique Beige & Gold', colorHex: '#d8c7a6', image: '/images/shawl_craft.jpg' },
      { colorName: 'Midnight Jet', colorHex: '#1f1f1f', image: '/images/shawl_craft.jpg' },
    ],
    isNewArrival: true,
    isBestseller: false,
    isOnSale: true,
    rating: 4.9,
    reviewsCount: 29,
    reviews: [
      {
        id: 'r9',
        author: 'Begum Salma Hashmi',
        city: 'Islamabad',
        rating: 5,
        date: '6 days ago',
        comment: 'Breathtaking artistry. The softness of the wool is genuine pashmina and the tilla embroidery is so fine.',
        verified: true,
      },
    ],
    careInstructions: [
      'Specialist dry clean only',
      'Do not hang; fold neatly in muslin cloth wrap',
    ],
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All Collections', count: 6 },
  { id: 'unstitched', name: 'Unstitched Luxury', count: 1 },
  { id: 'women-pret', name: 'Women Ready-To-Wear', count: 1 },
  { id: 'men', name: "Men's Traditional", count: 2 },
  { id: 'fragrances', name: 'Signature Fragrances', count: 1 },
  { id: 'shawls', name: 'Luxury Shawls', count: 1 },
];

export const SIZE_CHART = {
  women: [
    { size: 'XS', chest: '36"', length: '38"', shoulder: '14"', waist: '32"', hip: '38"' },
    { size: 'S', chest: '38"', length: '39"', shoulder: '14.5"', waist: '34"', hip: '40"' },
    { size: 'M', chest: '40"', length: '40"', shoulder: '15"', waist: '36"', hip: '42"' },
    { size: 'L', chest: '43"', length: '41"', shoulder: '16"', waist: '39"', hip: '45"' },
    { size: 'XL', chest: '46"', length: '42"', shoulder: '17"', waist: '42"', hip: '48"' },
  ],
  men: [
    { size: 'S', chest: '38"', length: '40"', shoulder: '17.5"', collar: '15"', sleeve: '24"' },
    { size: 'M', chest: '41"', length: '42"', shoulder: '18.5"', collar: '15.5"', sleeve: '24.5"' },
    { size: 'L', chest: '44"', length: '44"', shoulder: '19.5"', collar: '16.5"', sleeve: '25.5"' },
    { size: 'XL', chest: '47"', length: '45"', shoulder: '20.5"', collar: '17.5"', sleeve: '26"' },
    { size: 'XXL', chest: '50"', length: '46"', shoulder: '21.5"', collar: '18.5"', sleeve: '26.5"' },
  ],
};

export const CITIES_PAKISTAN = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Abbottabad',
  'Bahawalpur',
  'Sargodha',
  'Mirpur (AJK)',
  'Dubai (International)',
  'London (International)',
  'Riyadh (International)',
];

export const STORE_LOCATIONS = [
  {
    city: 'Karachi',
    name: 'Dolmen Mall Clifton Flagship',
    address: 'Ground Floor, Fashion Boulevard, Dolmen Mall Clifton, Sea View Rd',
    phone: '+92 21 3529 1100',
    hours: '11:00 AM – 11:00 PM',
  },
  {
    city: 'Lahore',
    name: 'MM Alam Road Boutique',
    address: '92-B2, Main MM Alam Road, Gulberg III, Lahore',
    phone: '+92 42 3578 4422',
    hours: '11:00 AM – 11:00 PM',
  },
  {
    city: 'Islamabad',
    name: 'The Centaurus Mall Atelier',
    address: 'First Floor, Wing B, The Centaurus Mall, Jinnah Avenue, F-8/4',
    phone: '+92 51 260 4880',
    hours: '11:00 AM – 10:30 PM',
  },
  {
    city: 'Dubai',
    name: 'Dubai Mall Flagship',
    address: 'Level 1, Near Fashion Avenue, The Dubai Mall, Downtown Dubai',
    phone: '+971 4 362 7500',
    hours: '10:00 AM – Midnight',
  },
];
